const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const matchingSchema = new Schema({
  requestId: { 
    type: String, 
    required: true, 
    unique: true, 
    index: true 
  },
  lostItemId: { 
    type: String, 
    required: true, 
    index: true 
  },
  foundItemId: { 
    type: String, 
    required: true, 
    index: true 
  },
  studentId: { 
    type: String, 
    required: true, 
    index: true 
  },
  staffId: String,
  matchConfidence: { 
    type: Number, 
    required: true 
  },
  matchReason: String,
  autoGenerated: { 
    type: Boolean, 
    default: true 
  },
  status: { 
    type: String, 
    enum: ['pending', 'confirmed', 'rejected', 'resolved'], 
    default: 'pending', 
    index: true 
  },
  studentResponse: String,
  studentResponseNote: String,
  confirmedAt: Date,
  expiresAt: Date,
  createdAt: { 
    type: Date, 
    default: Date.now, 
    index: true 
  },
  updatedAt: { 
    type: Date, 
    default: Date.now 
  }
}, { timestamps: true });

module.exports = mongoose.model('MatchingRequest', matchingSchema);

